# Form implementation generated from reading ui file 'greet_widget_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 904)
        self.main_frame = QtWidgets.QFrame(parent=Form)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 470, 900))
        self.main_frame.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.main_frame.setStyleSheet("background-color: rgb(190, 249, 255);\n"
"border-radius: 20")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.quitButton = QtWidgets.QPushButton(parent=self.main_frame)
        self.quitButton.setGeometry(QtCore.QRect(434, 10, 26, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius: 13px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"border: 1px solid rgba(0,0,0,100);\n"
"}")
        self.quitButton.setObjectName("quitButton")
        self.add_userButton = QtWidgets.QPushButton(parent=self.main_frame)
        self.add_userButton.setGeometry(QtCore.QRect(15, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.add_userButton.setFont(font)
        self.add_userButton.setStyleSheet("QPushButton {\n"
"}\n"
"QPushButton:hover {\n"
"font-weight: 700;\n"
"}")
        self.add_userButton.setObjectName("add_userButton")
        self.pushButton_1 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_1.setGeometry(QtCore.QRect(25, 320, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"  border-top-left-radius:20px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.entry_buttonGroup = QtWidgets.QButtonGroup(Form)
        self.entry_buttonGroup.setObjectName("entry_buttonGroup")
        self.entry_buttonGroup.addButton(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_2.setGeometry(QtCore.QRect(305, 320, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"  border-top-right-radius:20px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.entry_buttonGroup.addButton(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_3.setGeometry(QtCore.QRect(165, 320, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.entry_buttonGroup.addButton(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_4.setGeometry(QtCore.QRect(25, 460, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.entry_buttonGroup.addButton(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_5.setGeometry(QtCore.QRect(305, 460, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.entry_buttonGroup.addButton(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_6.setGeometry(QtCore.QRect(165, 460, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.entry_buttonGroup.addButton(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_7.setGeometry(QtCore.QRect(25, 600, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.entry_buttonGroup.addButton(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_8.setGeometry(QtCore.QRect(165, 600, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.entry_buttonGroup.addButton(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_9.setGeometry(QtCore.QRect(305, 600, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.entry_buttonGroup.addButton(self.pushButton_9)
        self.pushButton_enter = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_enter.setGeometry(QtCore.QRect(25, 740, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_enter.setFont(font)
        self.pushButton_enter.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"  border-bottom-left-radius:20px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}\n"
"")
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.entry_buttonGroup.addButton(self.pushButton_enter)
        self.pushButton_0 = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_0.setGeometry(QtCore.QRect(165, 740, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.entry_buttonGroup.addButton(self.pushButton_0)
        self.pushButton_del = QtWidgets.QPushButton(parent=self.main_frame)
        self.pushButton_del.setGeometry(QtCore.QRect(305, 740, 140, 140))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(40)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius:0;\n"
"  border-bottom-right-radius:20px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"\n"
"}")
        self.pushButton_del.setObjectName("pushButton_del")
        self.entry_buttonGroup.addButton(self.pushButton_del)
        self.label = QtWidgets.QLabel(parent=self.main_frame)
        self.label.setGeometry(QtCore.QRect(0, 260, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.user_comboBox = QtWidgets.QComboBox(parent=self.main_frame)
        self.user_comboBox.setGeometry(QtCore.QRect(190, 100, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(28)
        self.user_comboBox.setFont(font)
        self.user_comboBox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.user_comboBox.setStyleSheet("QComboBox:drop-down {\n"
"                border: 0px;\n"
"            }\n"
"            QComboBox:down-arrow {\n"
"                width: 0px;\n"
"                height: 0px;\n"
"                border: 0px;\n"
"            }\n"
"            QComboBox:hover {\n"
"                border-radius: 0;\n"
"            }")
        self.user_comboBox.setObjectName("user_comboBox")
        self.user_picture = QtWidgets.QLabel(parent=self.main_frame)
        self.user_picture.setGeometry(QtCore.QRect(110, 90, 64, 64))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(22)
        self.user_picture.setFont(font)
        self.user_picture.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"border-radius:32px;")
        self.user_picture.setText("")
        self.user_picture.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_picture.setObjectName("user_picture")
        self.passw_lineEdit = QtWidgets.QLineEdit(parent=self.main_frame)
        self.passw_lineEdit.setGeometry(QtCore.QRect(0, 220, 471, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.passw_lineEdit.setFont(font)
        self.passw_lineEdit.setText("")
        self.passw_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.passw_lineEdit.setObjectName("passw_lineEdit")
        self.quitButton.raise_()
        self.pushButton_1.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_enter.raise_()
        self.pushButton_0.raise_()
        self.pushButton_del.raise_()
        self.label.raise_()
        self.user_comboBox.raise_()
        self.user_picture.raise_()
        self.passw_lineEdit.raise_()
        self.add_userButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.quitButton.setText(_translate("Form", "X"))
        self.add_userButton.setText(_translate("Form", "+"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "3"))
        self.pushButton_3.setText(_translate("Form", "2"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "6"))
        self.pushButton_6.setText(_translate("Form", "5"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_enter.setText(_translate("Form", "E"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_del.setText(_translate("Form", "<"))
        self.label.setText(_translate("Form", "Enter your PIN-code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
