# Form implementation generated from reading ui file 'main_widget_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 899)
        self.main_frame = QtWidgets.QFrame(parent=Form)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 470, 900))
        self.main_frame.setStyleSheet("background-color: rgb(190, 249, 255);\n"
"border-radius: 20")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.quitButton = QtWidgets.QPushButton(parent=self.main_frame)
        self.quitButton.setGeometry(QtCore.QRect(434, 10, 26, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("QPushButton {\n"
"  background-color:  rgb(136, 239, 255);\n"
"  border-radius: 13px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 100);\n"
"border: 1px solid rgba(0,0,0,100);\n"
"}")
        self.quitButton.setObjectName("quitButton")
        self.log_out_button = QtWidgets.QPushButton(parent=self.main_frame)
        self.log_out_button.setGeometry(QtCore.QRect(15, 10, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.log_out_button.setFont(font)
        self.log_out_button.setStyleSheet("QPushButton {\n"
"}\n"
"QPushButton:hover {\n"
"font-weight: 700;\n"
"}")
        self.log_out_button.setObjectName("log_out_button")
        self.tableView = QtWidgets.QTableView(parent=self.main_frame)
        self.tableView.setGeometry(QtCore.QRect(25, 100, 420, 771))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"")
        self.tableView.setObjectName("tableView")
        self.username_label = QtWidgets.QLabel(parent=self.main_frame)
        self.username_label.setGeometry(QtCore.QRect(0, 10, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.add_data_button = QtWidgets.QPushButton(parent=self.main_frame)
        self.add_data_button.setGeometry(QtCore.QRect(25, 74, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.add_data_button.setFont(font)
        self.add_data_button.setStyleSheet("  QPushButton {\n"
"  border-radius:0;\n"
"  border-top-left-radius:15;\n"
"  background-color:  rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(238, 238, 238);\n"
"}")
        self.add_data_button.setObjectName("add_data_button")
        self.split_line1 = QtWidgets.QFrame(parent=self.main_frame)
        self.split_line1.setGeometry(QtCore.QRect(50, 74, 1, 25))
        self.split_line1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.split_line1.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.split_line1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.split_line1.setObjectName("split_line1")
        self.separ_line = QtWidgets.QFrame(parent=self.main_frame)
        self.separ_line.setGeometry(QtCore.QRect(25, 99, 420, 1))
        self.separ_line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.separ_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separ_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.separ_line.setObjectName("separ_line")
        self.delete_data_button = QtWidgets.QPushButton(parent=self.main_frame)
        self.delete_data_button.setGeometry(QtCore.QRect(51, 74, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.delete_data_button.setFont(font)
        self.delete_data_button.setStyleSheet("  QPushButton {\n"
"  background-color:  rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(238, 238, 238);\n"
"}")
        self.delete_data_button.setObjectName("delete_data_button")
        self.split_line2 = QtWidgets.QFrame(parent=self.main_frame)
        self.split_line2.setGeometry(QtCore.QRect(76, 74, 1, 25))
        self.split_line2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.split_line2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.split_line2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.split_line2.setObjectName("split_line2")
        self.import_data_button = QtWidgets.QPushButton(parent=self.main_frame)
        self.import_data_button.setGeometry(QtCore.QRect(77, 74, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.import_data_button.setFont(font)
        self.import_data_button.setStyleSheet("  QPushButton {\n"
"  background-color:  rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(238, 238, 238);\n"
"}")
        self.import_data_button.setObjectName("import_data_button")
        self.split_line3 = QtWidgets.QFrame(parent=self.main_frame)
        self.split_line3.setGeometry(QtCore.QRect(102, 74, 1, 25))
        self.split_line3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.split_line3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.split_line3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.split_line3.setObjectName("split_line3")
        self.spacer1 = QtWidgets.QFrame(parent=self.main_frame)
        self.spacer1.setGeometry(QtCore.QRect(103, 74, 180, 25))
        self.spacer1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spacer1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.spacer1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.spacer1.setObjectName("spacer1")
        self.split_line4 = QtWidgets.QFrame(parent=self.main_frame)
        self.split_line4.setGeometry(QtCore.QRect(283, 74, 1, 25))
        self.split_line4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.split_line4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.split_line4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.split_line4.setObjectName("split_line4")
        self.search_edit = QtWidgets.QLineEdit(parent=self.main_frame)
        self.search_edit.setGeometry(QtCore.QRect(284, 74, 161, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.search_edit.setFont(font)
        self.search_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0;\n"
"border-top-right-radius:15;")
        self.search_edit.setObjectName("search_edit")
        self.info_label = QtWidgets.QLabel(parent=self.main_frame)
        self.info_label.setGeometry(QtCore.QRect(102, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(11)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.username_label.raise_()
        self.quitButton.raise_()
        self.log_out_button.raise_()
        self.tableView.raise_()
        self.add_data_button.raise_()
        self.split_line1.raise_()
        self.separ_line.raise_()
        self.delete_data_button.raise_()
        self.split_line2.raise_()
        self.import_data_button.raise_()
        self.split_line3.raise_()
        self.spacer1.raise_()
        self.split_line4.raise_()
        self.search_edit.raise_()
        self.info_label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.quitButton.setText(_translate("Form", "X"))
        self.log_out_button.setText(_translate("Form", "⮀"))
        self.username_label.setText(_translate("Form", "Username"))
        self.add_data_button.setText(_translate("Form", "+"))
        self.delete_data_button.setText(_translate("Form", "-"))
        self.import_data_button.setText(_translate("Form", "~"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
