# Form implementation generated from reading ui file 'password_dialog_design_2.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 410)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 415, 410))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(190, 249, 255);\n"
"border-radius: 20;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 361, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 2, 1, 1, 1)
        self.descr_lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descr_lineEdit.setFont(font)
        self.descr_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.descr_lineEdit.setObjectName("descr_lineEdit")
        self.gridLayout.addWidget(self.descr_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_lineEdit.setFont(font)
        self.login_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.gridLayout.addWidget(self.login_lineEdit, 1, 1, 1, 1)
        self.show_char_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.show_char_button.setFont(font)
        self.show_char_button.setStyleSheet("QPushButton {\n"
"}\n"
"QPushButton:hover {\n"
"font-weight: 700;\n"
"}")
        self.show_char_button.setObjectName("show_char_button")
        self.gridLayout.addWidget(self.show_char_button, 2, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 360, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 221, 255, 75);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.create_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_button.sizePolicy().hasHeightForWidth())
        self.create_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgba(0, 221, 255, 75);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}")
        self.create_button.setObjectName("create_button")
        self.horizontalLayout.addWidget(self.create_button)
        self.error_label = QtWidgets.QLabel(parent=self.frame)
        self.error_label.setGeometry(QtCore.QRect(0, 335, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.error_label.setFont(font)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox.setGeometry(QtCore.QRect(30, 220, 371, 121))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox.setStyleSheet("border-radius: 0;")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.generate_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.generate_button.setGeometry(QtCore.QRect(222, 39, 141, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_button.sizePolicy().hasHeightForWidth())
        self.generate_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.generate_button.setFont(font)
        self.generate_button.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgba(0, 221, 255, 75);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}")
        self.generate_button.setObjectName("generate_button")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(60, 38, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.length_spinBox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.length_spinBox.setGeometry(QtCore.QRect(9, 38, 43, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_spinBox.sizePolicy().hasHeightForWidth())
        self.length_spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.length_spinBox.setFont(font)
        self.length_spinBox.setAccessibleName("")
        self.length_spinBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.length_spinBox.setStyleSheet("QSpinBox{\n"
"border-radius: 3px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QSpinBox::up-button{\n"
"background-color:  rgba(0, 221, 255, 75);\n"
"border: 1px solid rgba(0, 221, 255, 150); \n"
"border-radius:2px;\n"
"border-bottom-left-radius:0;\n"
"border-bottom-right-radius:0;\n"
"height:11px;\n"
"}\n"
"QSpinBox::down-button{\n"
"background-color:  rgba(0, 221, 255, 75);\n"
"border: 1px solid rgba(0, 221, 255, 150); \n"
"border-radius:2px;\n"
"border-top-left-radius:0;\n"
"border-top-right-radius:0;\n"
"height:11px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"                width: 0px;\n"
"                height: 0px;\n"
"                image\n"
"            }")
        self.length_spinBox.setWrapping(False)
        self.length_spinBox.setFrame(True)
        self.length_spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.length_spinBox.setReadOnly(False)
        self.length_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.length_spinBox.setAccelerated(False)
        self.length_spinBox.setProperty("showGroupSeparator", False)
        self.length_spinBox.setMaximum(32)
        self.length_spinBox.setProperty("value", 8)
        self.length_spinBox.setObjectName("length_spinBox")
        self.symb_checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.symb_checkBox.setGeometry(QtCore.QRect(204, 80, 85, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.symb_checkBox.setFont(font)
        self.symb_checkBox.setChecked(True)
        self.symb_checkBox.setObjectName("symb_checkBox")
        self.digits_checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.digits_checkBox.setGeometry(QtCore.QRect(139, 80, 48, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.digits_checkBox.setFont(font)
        self.digits_checkBox.setChecked(True)
        self.digits_checkBox.setObjectName("digits_checkBox")
        self.lower_checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.lower_checkBox.setGeometry(QtCore.QRect(10, 80, 47, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.lower_checkBox.setFont(font)
        self.lower_checkBox.setChecked(True)
        self.lower_checkBox.setObjectName("lower_checkBox")
        self.upper_checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.upper_checkBox.setGeometry(QtCore.QRect(75, 80, 50, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.upper_checkBox.setFont(font)
        self.upper_checkBox.setChecked(True)
        self.upper_checkBox.setObjectName("upper_checkBox")
        self.label_5.raise_()
        self.length_spinBox.raise_()
        self.generate_button.raise_()
        self.symb_checkBox.raise_()
        self.lower_checkBox.raise_()
        self.digits_checkBox.raise_()
        self.upper_checkBox.raise_()
        self.error_label.raise_()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Description"))
        self.label_2.setText(_translate("Dialog", "Login"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.show_char_button.setText(_translate("Dialog", "👁"))
        self.cancel_button.setText(_translate("Dialog", "OK"))
        self.create_button.setText(_translate("Dialog", "Create"))
        self.groupBox.setTitle(_translate("Dialog", "Generate password"))
        self.generate_button.setText(_translate("Dialog", "Generate"))
        self.label_5.setText(_translate("Dialog", "Password length"))
        self.symb_checkBox.setText(_translate("Dialog", "!#@$%_"))
        self.digits_checkBox.setText(_translate("Dialog", "0-9"))
        self.lower_checkBox.setText(_translate("Dialog", "a-z"))
        self.upper_checkBox.setText(_translate("Dialog", "A-Z"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
