# Form implementation generated from reading ui file 'user_creation_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(414, 300)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 415, 300))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(190, 249, 255);\n"
"border-radius: 20;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 220, 361, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 221, 255, 75);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.create_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgba(0, 221, 255, 75);\n"
"border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}")
        self.create_button.setObjectName("create_button")
        self.horizontalLayout.addWidget(self.create_button)
        self.error_label = QtWidgets.QLabel(parent=self.frame)
        self.error_label.setGeometry(QtCore.QRect(0, 200, 415, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        self.error_label.setFont(font)
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(31, 92, 92, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.user_lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.user_lineEdit.setGeometry(QtCore.QRect(138, 36, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.password_lineEdit.setGeometry(QtCore.QRect(138, 94, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.show_char_button = QtWidgets.QPushButton(parent=self.frame)
        self.show_char_button.setGeometry(QtCore.QRect(368, 94, 22, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.show_char_button.setFont(font)
        self.show_char_button.setStyleSheet("QPushButton {\n"
"}\n"
"QPushButton:hover {\n"
"font-weight: 700;\n"
"}")
        self.show_char_button.setObjectName("show_char_button")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(31, 34, 97, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(31, 150, 34, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.color_pick_button = QtWidgets.QPushButton(parent=self.frame)
        self.color_pick_button.setGeometry(QtCore.QRect(368, 36, 22, 22))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(13)
        self.color_pick_button.setFont(font)
        self.color_pick_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 221, 255, 75);\n"
"border-radius:9;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: rgba(0, 221, 255, 150);\n"
"}")
        self.color_pick_button.setObjectName("color_pick_button")
        self.pin_lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.pin_lineEdit.setGeometry(QtCore.QRect(138, 152, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pin_lineEdit.setFont(font)
        self.pin_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.pin_lineEdit.setObjectName("pin_lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancel_button.setText(_translate("Dialog", "OK"))
        self.create_button.setText(_translate("Dialog", "Create"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.show_char_button.setText(_translate("Dialog", "👁"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "PIN"))
        self.color_pick_button.setText(_translate("Dialog", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
